### ISSUE TITLE
Cannot npm install due to read-only file system

### ISSUE THREAD

**Issue by psurma** [stelligent/dromedary-serverless#3]
I get to the "npm install" action but that fails due to a read-only file system, any ideas?

This is the log:
`
npm ERR! Linux 4.1.19-24.31.amzn1.x86_64 
npm ERR! argv "/usr/local/lib64/node-v4.3.x/bin/node" "/tmp/source/node_modules/npm/bin/npm-cli.js" "install" 
npm ERR! node v4.3.2 
npm ERR! npm v2.15.9 
npm ERR! path /home/sbx_user1050
npm ERR! code EROFS 
npm ERR! errno -30 
npm ERR! syscall mkdir

npm ERR! rofs EROFS: read-only file system, mkdir '/home/sbx_user1050' 
npm ERR! rofs This is most likely not a problem with npm itself 
npm ERR! rofs and is related to the file system being read-only. 
npm ERR! rofs  
npm ERR! rofs Often virtualized file systems, or other file systems 
npm ERR! rofs that don't support symlinks, give this error. 
 npm ERR! Please include the following file with any support request: 
npm ERR! /tmp/source/npm-debug.log

{
    "errorMessage": "\"Error(226) -      /tmp/source/npm-debug.log\n\""
}
`

**Comment by cplee** [comment]
@psurma should be fixed now!
